// This file is autogenerated.
declare module "*.module.css" {
    const title: string;
    const small: string;
    const medium: string;
    const large: string;
    const left: string;
    const right: string;
    const center: string;
    const sp_left: string;
    const sp_right: string;
    const sp_center: string;
    const left: string;
    const right: string;
    const center: string;

    export {
        title,
        small,
        medium,
        large,
        left,
        right,
        center,
        sp_left,
        sp_right,
        sp_center,
        left,
        right,
        center,
    }
}
