// This file is autogenerated.
declare module "*.module.css" {
    const block: string;
    const inline_block: string;
    const small: string;
    const medium: string;
    const large: string;
    const sp_small: string;
    const sp_medium: string;
    const sp_large: string;
    const hover: string;
    const small: string;
    const medium: string;
    const large: string;

    export {
        block,
        inline_block,
        small,
        medium,
        large,
        sp_small,
        sp_medium,
        sp_large,
        hover,
        small,
        medium,
        large,
    }
}
