// This file is autogenerated.
declare module "*.module.css" {
    const container: string;
    const form_container: string;
    const contact_info_container: string;
    const input: string;
    const input_small: string;
    const input_large: string;
    const icon_text_container: string;
    const icon: string;
    const container: string;
    const input_small: string;

    export {
        container,
        form_container,
        contact_info_container,
        input,
        input_small,
        input_large,
        icon_text_container,
        icon,
        container,
        input_small,
    }
}
