// This file is autogenerated.
declare module "*.module.css" {
    const container: string;
    const layout: string;
    const layout_show: string;
    const layout_adjust: string;
    const nav_items: string;
    const nav_item: string;
    const logo_container: string;
    const sp_menu: string;
    const sp_menu_hide: string;
    const sp_logo: string;
    const sp_logo_hide: string;
    const sp_menu_toggle: string;
    const header_hide: string;
    const vertical_align: string;
    const show_menu_top: string;
    const container: string;
    const layout: string;
    const layout_adjust: string;
    const logo_container: string;
    const nav_items: string;
    const sp_menu: string;
    const header_hide: string;
    const nav_item: string;
    const logo_container: string;
    const vertical_align: string;
    const show_menu_top: string;

    export {
        container,
        layout,
        layout_show,
        layout_adjust,
        nav_items,
        nav_item,
        logo_container,
        sp_menu,
        sp_menu_hide,
        sp_logo,
        sp_logo_hide,
        sp_menu_toggle,
        header_hide,
        vertical_align,
        show_menu_top,
        container,
        layout,
        layout_adjust,
        logo_container,
        nav_items,
        sp_menu,
        header_hide,
        nav_item,
        logo_container,
        vertical_align,
        show_menu_top,
    }
}
