// This file is autogenerated.
declare module "*.module.css" {
    const red_test: string;
    const blue_test: string;
    const green_test: string;

    export {
        red_test,
        blue_test,
        green_test,
    }
}
