// This file is autogenerated.
declare module "*.module.css" {
    const container: string;
    const icon_link_container: string;
    const info_container: string;
    const info_item: string;
    const copyright: string;
    const dividing_line: string;

    export {
        container,
        icon_link_container,
        info_container,
        info_item,
        copyright,
        dividing_line,
    }
}
