// This file is autogenerated.
declare module "*.module.css" {
    const container: string;
    const inner_container: string;
    const hover: string;

    export {
        container,
        inner_container,
        hover,
    }
}
