// This file is autogenerated.
declare module "*.module.css" {
    const width_wrapper: string;
    const footer_width_wrapper: string;
    const content_width_wrapper: string;

    export {
        width_wrapper,
        footer_width_wrapper,
        content_width_wrapper,
    }
}
